### ISSUE TITLE
NPE on vsd.Close

### ISSUE THREAD

**Issue by mauhiz** [changeworld/visio2pdf_cl#20]
Found this during execution:

    visio2pdf.rb:47:in `visio2pdf_exec': undefined method `Close' for nil:NilClass (NoMethodError)
	from visio2pdf.rb:31:in `block in visio2pdf'
	from visio2pdf.rb:29:in `each'
	from visio2pdf.rb:29:in `visio2pdf'
	from visio2pdf.rb:21:in `visio2pdf_controller'
	from visio2pdf.rb:58:in `<main>'

**Comment by changeworld** [comment]
Thanks.

Please tell me the version of Windows, Visio.
